"""lucebox — host-side CLI for the lucebox-hub container.

Runs inside the container; the host wrapper at ../lucebox.sh handles `docker
run` plumbing and systemd integration. This package owns: TOML config, the
host-derived DFLASH_* serve heuristic, docker daemon calls (via the mounted
socket), and model download. The empirical autotune sweep, profiling, and
agent-client launchers land in follow-up PRs.
"""

# Version is generated by hatch-vcs at build time into _version.py.
# Fresh source-tree checkouts before any build will not yet have the
# file — fall back to a dev marker so imports don't break.
try:
    from lucebox._version import __version__
except ImportError:
    __version__ = "0.0.0.dev0+unbuilt"
