"""luce-bench — capability benchmarks for chat-completion endpoints.

Quick start:

    from lucebench.areas import ds4_eval
    from lucebench.runner import run_case

    cases = ds4_eval.load_cases()
    rows = [run_case(url="http://localhost:8080", case=c, model="dflash")
            for c in cases]

Or via CLI:

    lucebench --url http://localhost:8080 --area ds4-eval --model dflash

The package vendors evaluation fixtures from upstream MIT-licensed
projects (antirez/ds4, openai/human-eval, antoinezambelli/forge). See
NOTICE for attribution.
"""

# Version is generated by hatch-vcs at build time into _version.py.
# Fresh source-tree checkouts before any build will not yet have the
# file — fall back to a dev marker so imports don't break.
try:
    from lucebench._version import __version__
except ImportError:
    __version__ = "0.0.0.dev0+unbuilt"
